name: Deploy with Token

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace Token placeholder
        run: sed -i "s/___AIRTABLE_TOKEN___/${{ secrets.AIRTABLE_TOKEN }}/g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: main  # 如果你的 Pages 部署分支是 main，请改为 main
